import Link from "next/link";

import {
  annualDropDecisions,
  draftBoard,
  golfers,
  leagueTerm,
  majors,
  members,
  replacementDraftPicks,
  rosters,
} from "@/lib/data";
import {
  buildPayoutDecision,
  getDraftBoardForSeason,
  getDropDecisionsForSeason,
  getMemberRosterForYear,
  getSeasonMajors,
} from "@/lib/league";

const seasonYear = 2025;

export default function Season2025Page() {
  const golfersById = new Map(golfers.map((golfer) => [golfer.id, golfer]));
  const membersById = new Map(members.map((member) => [member.id, member]));

  const seasonMajors = getSeasonMajors(majors, seasonYear);
  const draftBoard2025 = getDraftBoardForSeason(draftBoard, seasonYear);
  const dropDecisions = getDropDecisionsForSeason(
    annualDropDecisions,
    seasonYear,
  );
  const payoutDecisions = seasonMajors.map((major) =>
    buildPayoutDecision(major, leagueTerm, golfers, rosters, members),
  );

  const draftedWins = payoutDecisions.filter(
    ({ payoutEvent }) => payoutEvent.isDraftedWinner,
  );
  const totalPayoutValue = draftedWins.reduce(
    (sum, { payoutEvent }) => sum + payoutEvent.totalPayout,
    0,
  );
  const biggestWinner = draftedWins.reduce<(typeof draftedWins)[number] | null>(
    (best, current) =>
      !best || current.payoutEvent.totalPayout > best.payoutEvent.totalPayout
        ? current
        : best,
    null,
  );

  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(255,250,240,0.97),_rgba(245,239,226,1)_42%,_rgba(226,214,184,0.98)_100%)]">
      <div className="mx-auto flex w-full max-w-7xl flex-col gap-8 px-5 py-6 sm:px-8 lg:px-10">
        <header className="overflow-hidden rounded-[2.5rem] border border-line bg-[linear-gradient(135deg,_rgba(23,60,39,0.97),_rgba(47,106,69,0.93)_55%,_rgba(112,138,94,0.92)_100%)] text-white shadow-[0_30px_90px_rgba(23,60,39,0.18)]">
          <div className="grid gap-8 px-6 py-8 sm:px-8 lg:grid-cols-[1.35fr_0.85fr] lg:px-10 lg:py-10">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.3em] text-emerald-100/85">
                Season Archive
              </p>
              <h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">
                The 2025 season that set the tone for the whole league term.
              </h1>
              <p className="mt-5 max-w-2xl text-sm leading-7 text-emerald-50/88 sm:text-base">
                This page preserves the original draft board, the 2025 rosters,
                every major outcome, and the offseason moves that shaped the
                2026 field. It is the historical starting point for the league,
                not just a snapshot of where things stand today.
              </p>

              <div className="mt-7 flex flex-wrap gap-3">
                <Link
                  href="/seasons"
                  className="rounded-full border border-white/20 bg-white/8 px-5 py-3 text-sm font-semibold text-white transition hover:bg-white/14"
                >
                  Back to seasons
                </Link>
                <Link
                  href="/data-check/2025"
                  className="rounded-full border border-white/20 bg-white/8 px-5 py-3 text-sm font-semibold text-white transition hover:bg-white/14"
                >
                  Open data check
                </Link>
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">
              <article className="rounded-[1.75rem] border border-white/12 bg-white/10 p-5 backdrop-blur-sm">
                <p className="text-xs uppercase tracking-[0.18em] text-emerald-100/80">
                  Drafted winning majors
                </p>
                <p className="mt-2 text-3xl font-semibold">{draftedWins.length}</p>
                <p className="mt-2 text-sm leading-6 text-emerald-50/82">
                  Out of {seasonMajors.length} majors, {draftedWins.length} winners were held by league teams.
                </p>
              </article>

              <article className="rounded-[1.75rem] border border-white/12 bg-white/10 p-5 backdrop-blur-sm">
                <p className="text-xs uppercase tracking-[0.18em] text-emerald-100/80">
                  Payouts created
                </p>
                <p className="mt-2 text-3xl font-semibold">${totalPayoutValue}</p>
                <p className="mt-2 text-sm leading-6 text-emerald-50/82">
                  Total league payout value generated by 2025 major winners.
                </p>
              </article>

              <article className="rounded-[1.75rem] border border-white/12 bg-white/10 p-5 backdrop-blur-sm sm:col-span-2 lg:col-span-1">
                <p className="text-xs uppercase tracking-[0.18em] text-emerald-100/80">
                  Biggest swing
                </p>
                <p className="mt-2 text-xl font-semibold">
                  {biggestWinner
                    ? `$${biggestWinner.payoutEvent.totalPayout} on ${seasonMajors.find((major) => major.id === biggestWinner.payoutEvent.majorId)?.name}`
                    : "No drafted winner"}
                </p>
                <p className="mt-2 text-sm leading-6 text-emerald-50/82">
                  {biggestWinner?.winnerMatch.member
                    ? `${biggestWinner.winnerMatch.member.displayName} held that winner.`
                    : "No drafted result recorded."}
                </p>
              </article>
            </div>
          </div>
        </header>

        <section className="grid gap-4 md:grid-cols-4">
          {[
            {
              label: "Original draft picks",
              value: draftBoard2025.length.toString(),
              note: "Full snake board saved pick by pick.",
            },
            {
              label: "Teams in play",
              value: members.length.toString(),
              note: "Six owners, six rosters, one four-year term.",
            },
            {
              label: "Offseason changes",
              value: `${dropDecisions.filter((decision) => decision.action === "drop").length}`,
              note: "Managers who made a 2025 drop-and-add move.",
            },
            {
              label: "Quiet offseason",
              value: `${dropDecisions.filter((decision) => decision.action === "keep").length}`,
              note: "Managers who stood pat after the 2025 majors.",
            },
          ].map((item) => (
            <article
              key={item.label}
              className="rounded-[1.5rem] border border-line bg-card/90 p-5"
            >
              <p className="text-sm font-medium text-muted">{item.label}</p>
              <p className="mt-2 text-3xl font-semibold">{item.value}</p>
              <p className="mt-2 text-sm leading-6 text-muted">{item.note}</p>
            </article>
          ))}
        </section>

        <section className="rounded-[2rem] border border-line bg-card/90 p-6 sm:p-8">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-accent">
                Season recap
              </p>
              <h2 className="mt-2 text-2xl font-semibold tracking-tight">
                The majors that defined 2025
              </h2>
            </div>
            <p className="text-sm text-muted">{leagueTerm.name}</p>
          </div>

          <div className="mt-6 grid gap-4 lg:grid-cols-2">
            {payoutDecisions.map(({ payoutEvent, obligations, winnerMatch }) => {
              const major = seasonMajors.find(
                (seasonMajor) => seasonMajor.id === payoutEvent.majorId,
              );
              const winnerName =
                winnerMatch.golfer?.name ?? major?.winnerName ?? "Unknown winner";

              return (
                <article
                  key={payoutEvent.id}
                  className="rounded-[1.5rem] border border-line bg-background/70 p-5"
                >
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">
                        {major?.name}
                      </p>
                      <h3 className="mt-2 text-xl font-semibold">{winnerName}</h3>
                    </div>
                    <div className="rounded-full border border-line bg-white/70 px-3 py-1 text-xs font-semibold uppercase tracking-[0.14em] text-muted">
                      {payoutEvent.isDraftedWinner ? "Settled payout" : "Undrafted result"}
                    </div>
                  </div>
                  <p className="mt-3 text-sm leading-6 text-muted">
                    {winnerMatch.member
                      ? `${winnerMatch.member.displayName} rostered the champion, creating ${obligations.length} payment obligations.`
                      : "No rostered team held the champion, so this major did not create a league payout."}
                  </p>
                  <p className="mt-3 text-base font-semibold text-foreground">
                    {payoutEvent.isDraftedWinner
                      ? `$${payoutEvent.amountPerLosingMember} from each member, $${payoutEvent.totalPayout} total`
                      : "No payout event"}
                  </p>
                </article>
              );
            })}
          </div>
        </section>

        <section className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
          <section className="rounded-[2rem] border border-line bg-card/90 p-6 sm:p-8">
            <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
              <div>
                <p className="text-sm font-semibold uppercase tracking-[0.2em] text-accent">
                  Original draft
                </p>
                <h2 className="mt-2 text-2xl font-semibold tracking-tight">
                  2025 opening board
                </h2>
              </div>
              <p className="text-sm text-muted">
                The first page in the league story.
              </p>
            </div>

            <div className="mt-6 grid gap-3 md:grid-cols-2">
              {draftBoard2025.map((pick) => {
                const member = membersById.get(pick.memberId);
                const golfer = golfersById.get(pick.golferId);

                return (
                  <article
                    key={pick.id}
                    className="rounded-[1.25rem] border border-line bg-background/70 p-4"
                  >
                    <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted">
                      Pick {pick.pickNumber}
                    </p>
                    <p className="mt-2 text-lg font-semibold">
                      {golfer?.name ?? pick.golferId}
                    </p>
                    <p className="mt-1 text-sm text-muted">
                      {member?.displayName} • {pick.teamName}
                    </p>
                  </article>
                );
              })}
            </div>
          </section>

          <section className="rounded-[2rem] border border-line bg-card/90 p-6 sm:p-8">
            <p className="text-sm font-semibold uppercase tracking-[0.2em] text-accent">
              Team rosters
            </p>
            <h2 className="mt-2 text-2xl font-semibold tracking-tight">
              Who each manager carried in 2025
            </h2>

            <div className="mt-6 grid gap-4">
              {members.map((member) => {
                const memberGolfers = getMemberRosterForYear(
                  member.id,
                  rosters,
                  golfers,
                  seasonYear,
                );

                return (
                  <article
                    key={member.id}
                    className="rounded-[1.5rem] border border-line bg-background/70 p-5"
                  >
                    <div className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between">
                      <div>
                        <p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">
                          {member.teamName}
                        </p>
                        <h3 className="mt-1 text-lg font-semibold">
                          {member.displayName}
                        </h3>
                      </div>
                    </div>
                    <ul className="mt-4 grid gap-2 text-sm leading-6 text-muted sm:grid-cols-2">
                      {memberGolfers.map((golfer) => (
                        <li key={golfer.id}>{golfer.name}</li>
                      ))}
                    </ul>
                  </article>
                );
              })}
            </div>
          </section>
        </section>

        <section className="rounded-[2rem] border border-line bg-card/90 p-6 sm:p-8">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-accent">
            Offseason transition
          </p>
          <h2 className="mt-2 text-2xl font-semibold tracking-tight">
            The moves that set up 2026
          </h2>
          <p className="mt-3 max-w-3xl text-sm leading-7 text-muted sm:text-base">
            After the final 2025 major, managers could optionally drop one
            golfer. Five teams made a move, while Ed Buckingham stayed put.
          </p>

          <div className="mt-6 grid gap-4 lg:grid-cols-2">
            {members.map((member) => {
              const dropDecision = dropDecisions.find(
                (decision) => decision.memberId === member.id,
              );
              const replacementPick = replacementDraftPicks.find(
                (pick) => pick.memberId === member.id && pick.seasonYear === seasonYear,
              );
              const droppedGolfer = dropDecision?.droppedGolferId
                ? golfersById.get(dropDecision.droppedGolferId)
                : undefined;
              const addedGolfer = replacementPick
                ? golfersById.get(replacementPick.golferId)
                : undefined;

              return (
                <article
                  key={member.id}
                  className="rounded-[1.5rem] border border-line bg-background/70 p-5"
                >
                  <p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">
                    {member.teamName}
                  </p>
                  <h3 className="mt-2 text-xl font-semibold">{member.displayName}</h3>
                  {dropDecision?.action === "drop" ? (
                    <div className="mt-4 space-y-2 text-sm leading-6 text-muted">
                      <p>Dropped: {droppedGolfer?.name ?? "Unknown golfer"}</p>
                      <p>Added: {addedGolfer?.name ?? "Unknown golfer"}</p>
                      <p>Replacement order: {replacementPick?.draftOrder ?? "Not recorded"}</p>
                    </div>
                  ) : (
                    <p className="mt-4 text-sm leading-6 text-muted">
                      No change. The 2025 roster rolled directly into 2026.
                    </p>
                  )}
                </article>
              );
            })}
          </div>
        </section>
      </div>
    </main>
  );
}
